`timescale 1ns / 1ps
`include "io_def.vh"
//==============================================================================
// Module:      top
// File:        top.v
// Description: Top-level for FPGA MEM-VGA project (Nexys A7-100T)
//
// Clock domains (all generated by the 'pll' Clocking Wizard IP):
//   clk_mem (200 MHz, CLKOUT1) - MIG memory core clock
//   clk_cpu (100 MHz, CLKOUT2) - MIG UI clock; memory_manager; sd_sync
//   clk_sd  ( 50 MHz, CLKOUT3) - SD card reader (fpga_top inside sd_interface)
//   clk_vga ( 25 MHz, CLKOUT4) - VGA pixel clock; vga_controller
//
// CDC crossings handled by:
//   sd_sync        : clk_sd  -> clk_cpu  (sd_data, sd_lineflag)
//   vga_controller : clk_cpu -> clk_vga  (display_words, display_valid - 2FF inside VGA)
//   resetn         : async button -> clk_cpu via 3-FF stretch in mig_example_top
//                    async button -> clk_vga via ff_sync (held until pll locked)
//
// Module hierarchy:
//   top
//   ├── pll          (Clocking Wizard IP: 100MHz -> clk_mem/clk_cpu/clk_sd/clk_vga)
//   ├── sd_interface (wraps fpga_top / sd_file_reader)
//   ├── sd_sync      (CDC: clk_sd -> clk_cpu)
//   ├── memory_manager
//   ├── ram_interface (wraps mig_example_top / mem_example)
//   └── vga_controller
//==============================================================================

module top (
    // -------------------------------------------------------------------------
    // Board clock & reset
    // -------------------------------------------------------------------------
    input  wire        CLK100MHZ,       // 100 MHz system clock
    input  wire        CPU_RESETN,      // Active-low reset button

    // -------------------------------------------------------------------------
    // Push buttons (active-high on Nexys A7)
    // -------------------------------------------------------------------------
    input  wire        BTNC,
    input  wire        BTNU,
    input  wire        BTND,
    input  wire        BTNL,
    input  wire        BTNR,

    // -------------------------------------------------------------------------
    // SD card
    // -------------------------------------------------------------------------
    output wire        SD_RESET,        // sdcard_pwr_n (active-low power)
    output wire        SD_CLK,
    inout  wire        SD_CMD,          // sdcmd
    input  wire        SD_DAT0,         // sddat0 (MISO)
    output wire        SD_DAT1,
    output wire        SD_DAT2,
    output wire        SD_DAT3,

    // -------------------------------------------------------------------------
    // DDR2 SDRAM (MT47H64M16HR-25E)
    // -------------------------------------------------------------------------
    inout  wire [15:0] ddr2_dq,
    inout  wire [1:0]  ddr2_dqs_n,
    inout  wire [1:0]  ddr2_dqs_p,
    output wire [12:0] ddr2_addr,
    output wire [2:0]  ddr2_ba,
    output wire        ddr2_ras_n,
    output wire        ddr2_cas_n,
    output wire        ddr2_we_n,
    output wire        ddr2_ck_p,
    output wire        ddr2_ck_n,
    output wire        ddr2_cke,
    output wire        ddr2_cs_n,
    output wire [1:0]  ddr2_dm,
    output wire        ddr2_odt,

    // -------------------------------------------------------------------------
    // VGA
    // -------------------------------------------------------------------------
    output wire [3:0]  VGA_R,
    output wire [3:0]  VGA_G,
    output wire [3:0]  VGA_B,
    output wire        VGA_HS,
    output wire        VGA_VS,

    // -------------------------------------------------------------------------
    // Debug LEDs  (16-bit; driven from ram_interface)
    // -------------------------------------------------------------------------
    output wire [15:0] LED
);

    // =========================================================================
    // Clock Generation  ('pll' Clocking Wizard IP, clk_wiz:6.0)
    //
    // Input : CLK100MHZ  (100 MHz board oscillator)
    // resetn: active-low reset port (named 'resetn' in the IP configuration)
    // locked: asserts high when all output clocks are stable
    //
    // Outputs (all buffered by BUFG inside the IP):
    //   clk_mem  (CLKOUT1) = 200 MHz  -> MIG memory core clock
    //   clk_cpu  (CLKOUT2) = 100 MHz  -> MIG UI clock, memory_manager, sd_sync
    //   clk_sd   (CLKOUT3) =  50 MHz  -> SD card reader
    //   clk_vga  (CLKOUT4) =  25 MHz  -> VGA pixel clock, vga_controller
    // =========================================================================
    wire clk_mem;
    wire clk_cpu;
    wire clk_sd;
    wire clk_vga;
    wire pll_locked;

    pll u_pll (
        .clk_in1  (CLK100MHZ),
        .resetn   (CPU_RESETN),   // active-low reset (matches RESET_PORT in XCI)
        .locked   (pll_locked),
        .clk_mem  (clk_mem),
        .clk_cpu  (clk_cpu),
        .clk_sd   (clk_sd),
        .clk_vga  (clk_vga)
    );

    // =========================================================================
    // Reset synchronization
    //   - CPU_RESETN is active-low from the board button.
    //   - mig_example_top already stretches resetn for clk_cpu internally.
    //   - For clk_vga we sync using ff_sync (active-high rst_p interface),
    //     held in reset until the PLL is locked.
    // =========================================================================
    wire resetn = CPU_RESETN;           // active-low, used by clk_cpu domain

    // Synchronize active-high reset into clk_vga domain
    wire rst_vga_p;                     // active-high reset for clk_vga domain
    ff_sync #(.WIDTH(1)) u_rst_vga_sync (
        .clk      (clk_vga),
        .rst_p    (~pll_locked),        // hold in reset until PLL locked
        .in_async (~CPU_RESETN),        // active-high version of board reset
        .out      (rst_vga_p)
    );
    wire resetn_vga = ~rst_vga_p;      // back to active-low for vga_controller

    // =========================================================================
    // SD Interface  (runs on clk_sd = 50 MHz from PLL CLKOUT3)
    // Outputs:
    //   sd_data    [31:0]  - one assembled 32-bit hex word
    //   sd_lineflag        - toggle flag: new word available
    //   sd_finish          - SD read complete
    // =========================================================================
    wire [31:0] sd_data;
    wire        sd_lineflag;
    wire        sd_finish;
    wire        sd_run;

    // sd_run: held high after reset to keep fpga_top running
    assign sd_run = CPU_RESETN;

    sd_interface u_sd_interface (
        .clk_sd       (clk_sd),
        .resetn       (CPU_RESETN),
        .sdcard_pwr_n (SD_RESET),
        .sdclk        (SD_CLK),
        .sdcmd        (SD_CMD),
        .sddat0       (SD_DAT0),
        .sddat1       (SD_DAT1),
        .sddat2       (SD_DAT2),
        .sddat3       (SD_DAT3),
        .led          (),               // not connected to top-level LEDs
        .data         (sd_data),
        .sd_run       (sd_run),
        .sd_finish    (sd_finish),
        .lineflag     (sd_lineflag)
    );

    // =========================================================================
    // SD Sync  (CDC: clk_sd -> clk_cpu)
    // Synchronizes sd_data and the toggle sd_lineflag into clk_cpu domain,
    // producing a single-cycle pulse cpu_lineflag_pulse and stable cpu_data.
    // =========================================================================
    wire [31:0] cpu_sd_data;
    wire        cpu_lineflag_pulse;

    sd_sync u_sd_sync (
        .clk_cpu           (clk_cpu),
        .resetn            (resetn),
        .sd_data           (sd_data),
        .sd_lineflag       (sd_lineflag),
        .cpu_lineflag_pulse(cpu_lineflag_pulse),
        .cpu_data          (cpu_sd_data)
    );

    // =========================================================================
    // Memory Manager  (clk_cpu domain)
    // - Accepts synchronized SD words and writes them into DDR2 (addresses 0-3)
    // - After all 4 words written, continuously reads them back and assembles
    //   the 128-bit display_words bus for the VGA controller
    // =========================================================================
    wire [27:0] mm_mem_addr;
    wire [63:0] mm_mem_data_out;
    wire [63:0] mm_mem_data_in;
    wire        mm_wflag;
    wire        mm_rflag;
    wire        mm_writefini;
    wire        mm_readfini;
    wire [127:0] display_words;
    wire          display_valid;

    memory_manager u_memory_manager (
        .clk_mem      (clk_cpu),        // memory_manager runs on MIG UI clock
        .resetn       (resetn),

        // SD data (already in clk_cpu domain via sd_sync)
        .sd_data      (cpu_sd_data),
        .sd_lineflag  (cpu_lineflag_pulse),

        // DDR2 interface (to/from ram_interface)
        .mem_addr_out (mm_mem_addr),
        .mem_data_out (mm_mem_data_out),
        .mem_data_in  (mm_mem_data_in),
        .wflag        (mm_wflag),
        .rflag        (mm_rflag),
        .writefini    (mm_writefini),
        .readfini     (mm_readfini),

        // Display output -> vga_controller
        .display_words(display_words),
        .display_valid(display_valid)
    );

    // =========================================================================
    // RAM Interface  (wraps mig_example_top / mem_example)
    // Bridges memory_manager signals to the MIG DDR2 IP
    // =========================================================================
    wire        ram_ramflag;    // DDR2 init calibration complete (unused here)

    ram_interface u_ram_interface (
        .clk_mem          (clk_mem),
        .clk_cpu          (clk_cpu),
        .resetn           (resetn),
        .lineflag         (cpu_lineflag_pulse),  // pass through for mig_example_top
        .mem_addr_in      (mm_mem_addr),
        .mem_d_to_ram_in  (mm_mem_data_out),
        .mem_d_from_ram_out(mm_mem_data_in),
        .ramflag          (ram_ramflag),
        .rflag            (mm_rflag),
        .wflag            (mm_wflag),
        .readfini         (mm_readfini),
        .writefini        (mm_writefini),
        .led              (LED),

        // DDR2 physical pins
        .ddr2_dq          (ddr2_dq),
        .ddr2_dqs_n       (ddr2_dqs_n),
        .ddr2_dqs_p       (ddr2_dqs_p),
        .ddr2_addr        (ddr2_addr),
        .ddr2_ba          (ddr2_ba),
        .ddr2_ras_n       (ddr2_ras_n),
        .ddr2_cas_n       (ddr2_cas_n),
        .ddr2_we_n        (ddr2_we_n),
        .ddr2_ck_p        (ddr2_ck_p),
        .ddr2_ck_n        (ddr2_ck_n),
        .ddr2_cke         (ddr2_cke),
        .ddr2_cs_n        (ddr2_cs_n),
        .ddr2_dm          (ddr2_dm),
        .ddr2_odt         (ddr2_odt)
    );

    // =========================================================================
    // VGA Controller  (clk_vga domain)
    // Receives display_words from clk_cpu domain; handles CDC internally
    // via 2-FF synchronizer on display_words.
    // Buttons are raw board inputs; debouncing is done inside vga_controller.
    // =========================================================================
    vga_controller u_vga_controller (
        .clk_vga      (clk_vga),
        .resetn       (resetn_vga),

        // Raw button inputs (debounced internally)
        .BTNC         (BTNC),
        .BTNU         (BTNU),
        .BTND         (BTND),
        .BTNL         (BTNL),
        .BTNR         (BTNR),

        // Data from memory_manager (clk_cpu -> clk_vga CDC inside VGA module)
        .display_words(display_words),
        .display_valid(display_valid),

        // VGA outputs
        .RED          (VGA_R),
        .GRN          (VGA_G),
        .BLU          (VGA_B),
        .HSYNC        (VGA_HS),
        .VSYNC        (VGA_VS)
    );

endmodule