#include "cs2mv/sharecode.h"

#include <string>

#include "test_util.h"

using cs2mv::DecodeShareCode;
using cs2mv::EncodeShareCode;
using cs2mv::NormalizeShareCode;
using cs2mv::ShareCode;

namespace {

struct Vector {
  const char* code;
  unsigned long long match_id;
  unsigned long long outcome_id;
  unsigned int token;
};

// Generated by tools/../ref implementations and cross-checked against both
// ValvePython/csgo and akiver/csgo-sharecode, which agree on every one.
const Vector kVectors[] = {
    {"CSGO-Cji4Z-rQMJJ-s6Jyq-ovwoS-mJkDA", 3230353706079420417ull, 3230360566016770561ull, 22528},
    {"CSGO-AAAAA-AAAAA-AAAAA-AAAAA-AAAAA", 0ull, 0ull, 0},
    {"CSGO-caMKV-r664Q-ubqq5-XOEhk-OijDA", 1ull, 2ull, 3},
    {"CSGO-Acc38-83iaN-HmMno-7LBiJ-GwtGR", 18446744073709551615ull, 18446744073709551615ull, 65535},
    {"CSGO-ENVEO-jHLV8-KFDmG-hxUWE-jfJ5O", 3253932207440199901ull, 3253939001133793636ull, 44510},
    {"CSGO-yyLyW-QujpG-C2aJS-mYPsq-WrOKB", 15815331330105505042ull, 3374539154224371476ull, 62573},
    {"CSGO-FhRXq-xwJfJ-yGcRS-DC3eU-nTbYM", 9370697991746436789ull, 7380811927600231133ull, 42129},
    {"CSGO-2J2Rr-iCOVA-nKeMy-54caZ-eFwDM", 1227485345648460719ull, 9773908962303119998ull, 10690},
    {"CSGO-2bXba-HVYm3-OMzVG-Ec8x3-hz6bK", 17998699845554369430ull, 14046528605562450407ull, 60059},
    {"CSGO-cyPwC-HmvOL-AzKLe-SemRu-d5qQQ", 6451507751108320498ull, 14757941356081209442ull, 7603},
};

}  // namespace

TEST(ShareCodeDecodesKnownVectors) {
  for (const Vector& v : kVectors) {
    ShareCode code;
    std::string error;
    CHECK(DecodeShareCode(v.code, &code, &error));
    CHECK_EQ(error, std::string());
    CHECK_EQ(code.match_id, v.match_id);
    CHECK_EQ(code.outcome_id, v.outcome_id);
    CHECK_EQ(static_cast<unsigned int>(code.token), v.token);
  }
}

TEST(ShareCodeEncodesKnownVectors) {
  for (const Vector& v : kVectors) {
    ShareCode code;
    code.match_id = v.match_id;
    code.outcome_id = v.outcome_id;
    code.token = static_cast<std::uint16_t>(v.token);
    CHECK_EQ(EncodeShareCode(code), std::string(v.code));
  }
}

TEST(ShareCodeAcceptsLooseFormatting) {
  const char* forms[] = {
      "CSGO-Cji4Z-rQMJJ-s6Jyq-ovwoS-mJkDA",
      "Cji4Z-rQMJJ-s6Jyq-ovwoS-mJkDA",
      "Cji4ZrQMJJs6JyqovwoSmJkDA",
      "  CSGO-Cji4Z-rQMJJ-s6Jyq-ovwoS-mJkDA\n",
  };
  for (const char* form : forms) {
    ShareCode code;
    std::string error;
    CHECK(DecodeShareCode(form, &code, &error));
    CHECK_EQ(code.match_id, 3230353706079420417ull);
  }
}

TEST(ShareCodeNormalises) {
  std::string canonical;
  CHECK(NormalizeShareCode("Cji4ZrQMJJs6JyqovwoSmJkDA", &canonical, nullptr));
  CHECK_EQ(canonical, std::string("CSGO-Cji4Z-rQMJJ-s6Jyq-ovwoS-mJkDA"));
}

TEST(ShareCodeRejectsBadInput) {
  const char* bad[] = {
      "",
      "CSGO-",
      "CSGO-AAAAA-AAAAA-AAAAA-AAAAA",       // four groups, not five
      "CSGO-AAAAA-AAAAA-AAAAA-AAAAA-AAAAAA",// one character too many
      "CSGO-AAAAA-AAAAA-AAAAA-AAAAA-AAAAl", // 'l' is not in the alphabet
      "CSGO-AAAAA-AAAAA-AAAAA-AAAAA-AAAA0", // nor is '0'
      "not a share code at all",
  };
  for (const char* code : bad) {
    ShareCode decoded;
    std::string error;
    CHECK(!DecodeShareCode(code, &decoded, &error));
    CHECK(!error.empty());
  }
}

TEST(ShareCodeRoundTripsRandomValues) {
  // A simple xorshift keeps this deterministic without <random> ordering
  // differences between standard libraries.
  std::uint64_t state = 0x9E3779B97F4A7C15ull;
  auto next = [&state]() {
    state ^= state << 13;
    state ^= state >> 7;
    state ^= state << 17;
    return state;
  };
  for (int i = 0; i < 500; ++i) {
    ShareCode code;
    code.match_id = next();
    code.outcome_id = next();
    code.token = static_cast<std::uint16_t>(next());

    ShareCode decoded;
    std::string error;
    CHECK(DecodeShareCode(EncodeShareCode(code), &decoded, &error));
    CHECK_EQ(decoded.match_id, code.match_id);
    CHECK_EQ(decoded.outcome_id, code.outcome_id);
    CHECK_EQ(decoded.token, code.token);
  }
}
